### ISSUE TITLE
Dart build 0.7.1-alpha.1 does not compile

### ISSUE THREAD

**Issue by yholkamp** [ory/sdk#94] opened 2021-08-04 19:00 UTC
**Describe the bug**

The 0.7.1-alpha.1 build of the Dart Kratos client library does not compile as it calls an invalid method.

**To Reproduce**

1. Include the library in a Flutter project
2. Run `flutter build appbundle`
3. Observe the following errors:

        ../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ory_kratos_client-0.7.1-alpha.1/lib/model/generic_error.dart:101:20: Error: Method not found: 'Object.mapFromJson'.
                  : Object.mapFromJson(json[r'details']),                       
                           ^^^^^^^^^^^                                          
        ../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ory_kratos_client-0.7.1-alpha.1/lib/model/volume.dart:117:20: Error: Method not found: 'Object.mapFromJson'.
                  : Object.mapFromJson(json[r'Status']),                        
                           ^^^^^^^^^^^                                          
                                                                        
**Expected behavior**

These lines attempt to deserialize a map of string to object properties from JSON, in the case of Dart the goal should be a Map here and not an Object as the spec dictates. One way to adjust that may be to change such lines in to a `json[r'details'] as Map` cast rather, as the input is already deserialized and maybe in the right format. 

**Environment**

- Version: Flutter 2.0.2
- Dart v2.12.1

**Additional context**

The root cause seems to be with the code generator: 
- https://github.com/swagger-api/swagger-codegen/issues/9182 describes the same issue, as does
- https://github.com/OpenAPITools/openapi-generator/issues/9272

**Comment by aeneasr** [comment] 2021-08-04 20:02
Could you try alpha.3?

**Comment by yholkamp** [comment] 2021-08-05 11:05
@aeneasr I'm happy to but I'm not seeing that version released yet at https://pub.dev/packages/ory_kratos_client/versions, is that underway?

**Comment by aeneasr** [comment] 2021-08-05 13:55
Whoops, my bad, looks like I was in the future already. We only released 0.7.1 :D

**Comment by jld3103** [comment] 2021-08-12 08:01
I also get the same error. Could downgrading also help? From what I researched it is a bug in the openapi-generator, but maybe I'm wrong.

**Comment by aeneasr** [comment] 2021-08-12 11:24
Probably caused by: https://github.com/swagger-api/swagger-codegen/pull/7418#issuecomment-358648679

**Comment by aeneasr** [comment] 2021-08-12 11:27
I just saw that the `dart` generator is probably outdated and also does not support OAS3 which we are now using. It looks like we have some alternatives:

- https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/dart.md
- https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/dart-dio.md
- https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/dart-dio-next.md
- https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/dart-jaguar.md

I don't know any Dart so I don't know the differences between dio / dio-next and jaguar. From what I see on the forums, dart-dio looks like it's better supported?

**Comment by jld3103** [comment] 2021-08-12 11:50
Those are frameworks. I only know dio, but it's pretty good as far as I remember.

**Comment by yholkamp** [comment] 2021-08-12 12:12
@aeneasr since adding this ticket I've had success with the `dart2` generator. One limitation was the lack of `DELETE` call support  (for logout) but that's resolved in master via https://github.com/OpenAPITools/openapi-generator/pull/10100 , it will be in the 5.2.1 release but is not out yet. Once it's released I'd propose moving the dart client over to that, alternatively the generator works right now in 5.2.0 with the note that the logout endpoint fails.

**Comment by aeneasr** [comment] 2021-08-12 12:27
Ahhh, ok, that makes sense! Then yeah, all for going with dart2 generator!

**Comment by jld3103** [comment] 2021-08-12 12:27
But the generated code is dart 2 compliant (see the `@dart=2.0`) comments in the files.

**Comment by aeneasr** [comment] 2021-08-23 09:11
So should we change to the dart2 generator? It isn't documented yet :/

**Comment by aeneasr** [comment] 2021-08-23 15:15
Ok, so I have merged the changes and triggered a release. Let's see if it works now. A few questions from my side:

1. How would testing the SDK look like for Dart? Can we ensure that it compiles before we push it to remote?
2. Should we switch to dart2 and if so, are there some resources on its maturity? And how would we switch (couldn't find an officially supported page)
3. Can you check if the newest release compiles now?

**Comment by aeneasr** [comment] 2021-08-23 15:15
https://pub.dev/packages/ory_kratos_client/versions/0.7.1-alpha.2

**Comment by aeneasr** [comment] 2021-09-08 18:44
Superseded #109

**Closed by aeneasr** 2021-09-08 18:44 UTC
